version: "3.9"

services:
  web:
    ports:
      - "8081:8081"
    environment:
      spring_profiles_active: dev
  db:
    ports:
      - "3306:3306"
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d
      - data-dev:/var/lib/mysql
  adminer:
    ports:
      - "3081:8080"
volumes:
  data-dev: